import { Box, Button, Flex, FormControl, FormLabel, Heading, Input, Text, Textarea } from '@chakra-ui/react'
import Head from 'next/head'
import {  FunctionComponent } from 'react';
import { useForm } from 'react-hook-form';

// criando com Lib react-hook-form

interface IHomeProps{
  fistName: string,
  lastName: string,
  email: string,
  address: string,
  phone: string,
  description: string,
  onSubmit: () => void;
  handlerSubmit: () => void;
}

const  Cadastro: FunctionComponent<IHomeProps> = () => {

  const {register, handleSubmit} = useForm();
  const onSubmit = (data: object) => {
    console.log(data)
  }
 
  return (
    <>
      <Head>
        <title>Form com NextJS e Chakra UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Flex
          minHeight='100vh'
          width='full'
          align='center'
          justifyContent='center'
          backgroundColor='gray.900'
        >
          <Box px={12} py={12} width='full' maxWidth='450px' textAlign='center'
            boxShadow='lg' borderRadius='6px' background='gray.700'>
            <Heading>
              <Text color='gray.200' fontSize='2xl'>
                Formulário de Registro
              </Text>
            </Heading>
            <Box>
              <form action="" autoComplete='off' onSubmit={handleSubmit(onSubmit)}>
                <Flex justify='space-between'>
                <FormControl isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >First Name</FormLabel>
                  <Input 
                  type='text' 
                  border='none' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='first name'
                  {...register('fistName')}
     
                  />
                </FormControl>
                <FormControl  isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Last Name</FormLabel>
                  <Input 
                  type='text'
                  border='none' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Last name'
                  {...register('lastName')}
               />
                </FormControl>
                </Flex>
                <FormControl  isRequired marginTop='15px' >
                  <FormLabel color='gray.200' > Your e-mail</FormLabel>
                  <Input 
                  type='text' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your e-mail'
                  {...register('email')}
                 />
                </FormControl>
                <Flex justify='space-between' >
                <FormControl  isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Your address</FormLabel>
                  <Input 
                  type='text' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your address'
                  {...register('address')}
                />
                </FormControl>
                <FormControl  isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Your phone</FormLabel>
                  <Input 
                  type='number'
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your phone'
                  {...register('phone')}
             />
                </FormControl>
                </Flex>
                <FormControl  isRequired marginTop='15px'>
                  <FormLabel color='gray.200' >Your descript message</FormLabel>
                  <Textarea 
                    outline='none'   
                    bgColor='gray.900' 
                    focusBorderColor='gray.600' 
                    color='gray.200' 
                    placeholder='Your descript message'
                    resize='none'
                    {...register('description')}
                    />
                </FormControl>
        
                <Button
                  type='submit'
                  width='full'
                  bgColor='green.400'
                  mt={4}
                  color='gray.200'
                  _hover={{color: 'black'}}
                >Cadastro</Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  )
}

export default Cadastro;
